AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
PubkeyAuthentication yes
AllowUsers debian akriven-backup-anchor
AllowAgentForwarding no
AllowTcpForwarding local
GatewayPorts no
PermitTunnel no
X11Forwarding no
MaxAuthTries 3
MaxSessions 4
ClientAliveInterval 120
ClientAliveCountMax 3
LoginGraceTime 30
PermitEmptyPasswords no
