export const dashboardHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer"><title>Schema Guard Local Control Plane</title>
<style>body{font:15px system-ui;margin:2rem;max-width:1100px;color:#18212f}input,button{font:inherit;padding:.55rem}input{width:32rem;max-width:70%}button{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem;margin:1.5rem 0}.card{border:1px solid #dbe2ea;border-radius:10px;padding:1rem;background:#f8fafc;min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;overflow:auto;background:#111827;color:#e5e7eb;padding:1rem;border-radius:8px;font-size:12px;line-height:1.45}small{color:#526071}.bad{color:#a01616}</style></head>
<body><h1>Schema Guard local control plane</h1><p>Enter a tenant API key. It remains in this tab's memory and is sent only to this loopback origin.</p>
<input id="key" type="password" autocomplete="off" placeholder="sg_live_…"><button id="load">Load</button><p id="status"></p>
<div class="grid"><div class="card"><h2>Usage</h2><pre id="usage">—</pre></div><div class="card"><h2>Audit chain</h2><pre id="chain">—</pre></div><div class="card"><h2>Alerts</h2><pre id="alerts">—</pre></div></div>
<h2>Recent decisions</h2><pre id="audits">—</pre><small>No argument values are stored or shown.</small>
<script type="module">const q=id=>document.getElementById(id);const clearPanels=()=>{for(const id of['usage','chain','alerts','audits'])q(id).textContent='—'};async function get(path){const r=await fetch(path,{headers:{authorization:'Bearer '+q('key').value},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error);return j}q('load').onclick=async()=>{clearPanels();q('status').className='';q('status').textContent='Loading…';try{const [u,c,a,e]=await Promise.all([get('/v1/usage'),get('/v1/audits/verify'),get('/v1/audits?limit=25'),get('/v1/alerts')]);const audits=a.audits.map(({audit_id,occurred_at,decision,reason_code,repair_rules})=>({audit_id,occurred_at,decision,reason_code,repair_rules}));const alerts=e.alerts.map(({id,kind,severity,created_at,acknowledged_at,detail})=>({id,kind,severity,created_at,acknowledged_at,detail}));q('usage').textContent=JSON.stringify(u,null,2);q('chain').textContent=JSON.stringify(c,null,2);q('audits').textContent=JSON.stringify(audits,null,2);q('alerts').textContent=JSON.stringify(alerts,null,2);q('status').textContent='Loaded'}catch(e){clearPanels();q('status').className='bad';q('status').textContent=e.message}}</script></body></html>`;
